=== krrg/ancient-tiles-java/src/ancienttiles/tiles/mapgen/mapgen.xsd
<?xml version="1.0"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
    <xs:element name="ae">
        <xs:complexType>
            <xs:sequence>
                
                <xs:element name="map">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="layer" minOccurs='0'>
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="tile" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="attribute" maxOccurs="unbounded" type="xs:string"></xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="x" type="xs:int"></xs:attribute>
                                                <xs:attribute name="y" type="xs:int"></xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:string"></xs:attribute>
                                </xs:complexType>                         
                                
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="mapgen">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="layer" maxOccurs="unbounded" minOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="maprgb" maxOccurs="unbounded" minOccurs="0">                                        
                                        </xs:element>
                                    </xs:sequence>                                    
                                    <xs:attribute name="id" type="xs:string"></xs:attribute>
                                    <xs:attribute name="type" type="xs:string"></xs:attribute>
                                    <xs:attribute name="color" type="xs:string"></xs:attribute>
                                    <xs:attribute name="imgloc" type="xs:string"></xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== krrg/ancient-tiles-java/map.xml.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->


<ae
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='file:/users/guest/k/krr428/NetBeansProjects/AncientTiles/src/ancienttiles/tiles/mapgen/mapgen.xsd'>
    
    <mapgen>
        <layer id="00 Map" type="color" color=""></layer>
        <layer id="01 Floor" type="" ></layer>
        <layer id="02 Test" type="" ></layer>
    </mapgen>
    <map>
        <tile x="" y="">
            <attribute></attribute>
            <attribute></attribute>
            <attribute></attribute>
        </tile>
        <tile x="" y="">
            <attribute></attribute>
        </tile>
        <tile x="" y="">
            <attribute></attribute>
        </tile>
    </map>

</ae>
